# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=200)),
                ('drink_garnish', models.CharField(max_length=300)),
                ('drink_inst', models.CharField(max_length=300)),
                ('drink_glass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_name', models.CharField(max_length=50)),
                ('ing_amount', models.CharField(max_length=50)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.Drink')),
            ],
        ),
    ]
