# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_name', models.CharField(max_length=50)),
                ('ing_amount', models.CharField(max_length=50)),
            ],
        ),
    ]
