# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_remove_allingredients_ing_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='drink_url',
            field=models.CharField(default='default', max_length=80),
            preserve_default=False,
        ),
    ]
