# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drinks', '0004_drink_drink_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='drink_user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
