handlers:

- url: /static/drinks
  static_dir: drinks/static/drinks

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
  
- name: ssl
  version: latest


env_variables:
  DJANGO_SETTINGS_MODULE: 'drinksite.settings'
